# Generated by Django 4.2.4 on 2023-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=1000, null=True)),
                ('textfield', models.TextField(max_length=1000, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='s3://kukudku/complaints/')),
            ],
        ),
    ]
