# Generated by Django 4.2.2 on 2023-07-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0002_remove_shopmodel_shopid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='shopCode',
            field=models.CharField(max_length=500),
        ),
    ]
