# Generated by Django 4.2.2 on 2023-07-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0005_alter_shopmodel_shopcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='shopCode',
            field=models.IntegerField(null=True),
        ),
    ]
