# Generated by Django 4.2.2 on 2023-08-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0007_alter_shopmodel_shopcode_alter_shopmodel_shopname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopmodel',
            old_name='shopname',
            new_name='shopArea',
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='shopId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='shopLatitude',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='shopLongitude',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='shopName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='shopCode',
            field=models.IntegerField(null=True),
        ),
    ]
