# Generated by Django 4.2.2 on 2023-08-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0010_rename_shopaddress_shopmodel_shopname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shopModel',
            new_name='shoplistModel',
        ),
    ]
