# Generated by Django 4.2.2 on 2023-08-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='userId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
