# Generated by Django 4.2.2 on 2023-08-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usermodel_id_alter_usermodel_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='userRoles',
            fields=[
                ('userRoleId', models.IntegerField(primary_key=True, serialize=False)),
                ('roleID', models.IntegerField(null=True)),
                ('roleActiveYN', models.CharField(max_length=10, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
        ),
    ]
