# Generated by Django 4.2.2 on 2023-08-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroles',
            old_name='roleID',
            new_name='roleId',
        ),
    ]
