# Generated by Django 4.2.4 on 2023-09-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_roleid_userroles_roleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroles',
            old_name='userid',
            new_name='userId',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='userId',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
