# Generated by Django 4.2.1 on 2023-09-07 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slr.route'),
        ),
    ]
