# Generated by Django 4.2.1 on 2023-09-07 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slr', '0002_alter_shop_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slr.route', to_field='name'),
        ),
    ]
