# Generated by Django 4.2.1 on 2023-09-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slr', '0003_alter_route_name_alter_shop_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='route',
            field=models.CharField(max_length=255),
        ),
    ]
