# Generated by Django 4.2.4 on 2023-10-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slr', '0004_alter_shop_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
            preserve_default=False,
        ),
    ]
