# Generated by Django 4.2.2 on 2023-07-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=1000)),
                ('amount', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('typeofpayment', models.CharField(max_length=200)),
            ],
        ),
    ]
