# Generated by Django 4.2.2 on 2023-07-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='collection',
            new_name='collectionModel',
        ),
    ]
