# Generated by Django 4.2.2 on 2023-07-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_rename_collection_collectionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionmodel',
            old_name='typeofpayment',
            new_name='paymentmethod',
        ),
    ]
