# Generated by Django 4.2.2 on 2023-07-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_rename_typeofpayment_collectionmodel_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='shopId',
            field=models.IntegerField(null=True),
        ),
    ]
