# Generated by Django 4.2.2 on 2023-07-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_collectionmodel_shopid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='location',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='paymentmethod',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='shopId',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
