# Generated by Django 4.2.2 on 2023-07-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_alter_collectionmodel_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionmodel',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='collectionmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='collectionmodel',
            name='location',
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='lati',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='longi',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='paidamount',
            field=models.CharField(max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='paymentmethod',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('UPI', 'UPI')], max_length=200, null=True),
        ),
    ]
