# Generated by Django 4.2.2 on 2023-08-14 04:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_remove_collectionmodel_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='paymentmethod',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), size=None),
        ),
    ]
