# Generated by Django 4.2.2 on 2023-08-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_roleid_userroles_roleid'),
        ('collection', '0008_collectioninfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='colledtionSkipped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollectionDate', models.DateField()),
                ('CollectionTime', models.TimeField()),
                ('Remark', models.TextField()),
                ('Confirmed', models.CharField()),
                ('CollectionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collectioninfo')),
                ('shopId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collectionmodel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
        ),
    ]
