# Generated by Django 4.2.2 on 2023-08-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_rename_collectiondate_collectionskipped_collectiondate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionskipped',
            name='confirmed',
            field=models.CharField(null=True),
        ),
    ]
