# Generated by Django 4.2.4 on 2023-08-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_alter_collectionskipped_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioninfo',
            name='collectionId',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
