# Generated by Django 4.2.4 on 2023-09-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0016_alter_collectioninfo_collectionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioninfo',
            name='collectionId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
