# Generated by Django 4.2.4 on 2023-09-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_alter_collectioninfo_collectionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='shopId',
            field=models.IntegerField(max_length=500, null=True),
        ),
    ]
