# Generated by Django 4.2.4 on 2023-09-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0019_alter_collectionmodel_shopid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmodel',
            name='cheque_photo',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to='s3://kukudku/collection/cheques'),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='gpay_photo',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to='s3://kukudku/collection/gpay'),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='neft_imps_photo',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to='s3://kukudku/collection/neft_imps'),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='paytm_photo',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to='s3://kukudku/collection/paytm'),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='phonepe_photo',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to='s3://kukudku/collection/phonepe'),
        ),
    ]
