# Generated by Django 4.2.1 on 2023-06-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_password_loginmodel_pin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginmodel',
            old_name='PIN',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='loginmodel',
            old_name='USER_MOBILE_NO',
            new_name='username',
        ),
    ]
