# Generated by Django 4.2.2 on 2023-06-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_pin_loginmodel_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginmodel',
            old_name='password',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='loginmodel',
            old_name='username',
            new_name='user_mobile_no',
        ),
    ]
