# Generated by Django 4.2.2 on 2023-06-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_password_loginmodel_pin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginmodel',
            old_name='user_mobile_no',
            new_name='user_mobile_number',
        ),
    ]
