# Generated by Django 4.2.2 on 2023-07-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_loginmodel_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='pin',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='user_mobile_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
