# Generated by Django 4.2.2 on 2023-07-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_loginmodel_pin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginmodel',
            old_name='pin',
            new_name='user_pin',
        ),
    ]
