# Generated by Django 4.2.2 on 2023-07-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_routemodel_routeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemodel',
            name='RouteId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='RouteInfo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
