# Generated by Django 4.2.2 on 2023-08-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_alter_routemodel_routeid_alter_routemodel_routeinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routemodel',
            old_name='RouteInfo',
            new_name='RouteAreas',
        ),
        migrations.AddField(
            model_name='routemodel',
            name='RouteEndPoint',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='RouteName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='RouteStartPoint',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
