# Generated by Django 4.2.2 on 2023-08-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.IntegerField(null=True)),
                ('shopCode', models.IntegerField(null=True)),
                ('shopName', models.CharField(max_length=100, null=True)),
                ('shopArea', models.CharField(max_length=100, null=True)),
                ('shopLatitude', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('shopLongitude', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('shopAddress', models.CharField(max_length=100, null=True)),
                ('shopPincode', models.IntegerField(null=True)),
                ('shopDistance', models.IntegerField(null=True)),
                ('shopMobileNo', models.IntegerField(null=True)),
                ('shopAlternateNo', models.IntegerField(null=True)),
                ('shopOwnerId', models.IntegerField(null=True)),
                ('shopType', models.CharField(max_length=20, null=True)),
                ('shopStatus', models.CharField(max_length=15, null=True)),
                ('shopFlexibleRate', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
