# Generated by Django 4.2.2 on 2023-08-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopmodel',
            name='shopId',
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='shopAlternateNo',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='shopMobileNo',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='shopOwnerId',
            field=models.BigIntegerField(null=True),
        ),
    ]
