# Generated by Django 4.2.2 on 2023-08-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shopmodel_shopid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='shopCode',
            field=models.CharField(null=True),
        ),
    ]
