# Generated by Django 4.2.2 on 2023-08-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopmodel_shopcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopOwners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerId', models.CharField(max_length=100, null=True)),
                ('OwnerName', models.CharField(max_length=100, null=True)),
                ('OwnerContactNo', models.CharField(max_length=10, null=True)),
                ('OwnerAlternateNo', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
