# Generated by Django 4.2.2 on 2023-08-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shopowners'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopRouteId', models.CharField(max_length=10, null=True)),
                ('routeId', models.CharField(max_length=10, null=True)),
                ('shopId', models.CharField(max_length=10, null=True)),
                ('shopOrder', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='shopowners',
            old_name='OwnerAlternateNo',
            new_name='ownerAlternateNo',
        ),
        migrations.RenameField(
            model_name='shopowners',
            old_name='OwnerContactNo',
            new_name='ownerContactNo',
        ),
        migrations.RenameField(
            model_name='shopowners',
            old_name='OwnerId',
            new_name='ownerId',
        ),
        migrations.RenameField(
            model_name='shopowners',
            old_name='OwnerName',
            new_name='ownerName',
        ),
    ]
