# Generated by Django 4.2.2 on 2023-08-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shoproutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopowners',
            name='ownerId',
        ),
        migrations.RemoveField(
            model_name='shoproutes',
            name='shopRouteId',
        ),
    ]
