# Generated by Django 4.2.2 on 2023-08-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_shopowners_ownerid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.CharField(max_length=500, null=True)),
                ('shopBalance', models.BigIntegerField(null=True)),
            ],
        ),
    ]
