# Generated by Django 4.2.5 on 2023-10-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shopbalances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='shopAlternateNo',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='shopCode',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='shopMobileNo',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
