# Generated by Django 4.2.2 on 2023-07-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='finalizecollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashierId', models.CharField(max_length=500, null=True)),
                ('routeId', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
