# Generated by Django 4.2.2 on 2023-07-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.PositiveIntegerField(max_length=100)),
                ('date', models.DateField(verbose_name='')),
                ('remark', models.CharField(max_length=1000)),
                ('cashierId', models.PositiveIntegerField(max_length=10)),
            ],
        ),
    ]
