# Generated by Django 4.2.2 on 2023-07-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skipshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipmodel',
            name='cashierId',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='skipmodel',
            name='shopId',
            field=models.CharField(max_length=100),
        ),
    ]
