# Generated by Django 4.2.2 on 2023-07-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skipshop', '0003_alter_skipmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='skipmodel',
            name='routeId',
            field=models.IntegerField(null=True),
        ),
    ]
