# Generated by Django 4.2.2 on 2023-07-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skipshop', '0006_alter_skipmodel_cashierid_alter_skipmodel_shopid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipmodel',
            name='cashierId',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skipmodel',
            name='remark',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='skipmodel',
            name='routeId',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='skipmodel',
            name='shopId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
