# Generated by Django 4.2.2 on 2023-08-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skipshop', '0007_alter_skipmodel_cashierid_alter_skipmodel_remark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skipmodel',
            name='date',
        ),
    ]
