# Generated by Django 4.2.4 on 2023-09-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skipshop', '0008_remove_skipmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skipmodel',
            name='cashierId',
        ),
        migrations.RemoveField(
            model_name='skipmodel',
            name='routeId',
        ),
    ]
