# Generated by Django 4.2.4 on 2023-09-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skipshop', '0009_remove_skipmodel_cashierid_remove_skipmodel_routeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='skipmodel',
            name='cashierId',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='skipmodel',
            name='routeId',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
